name: Multi-platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        build_type: [ Release ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up fontconfig
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libfontconfig1-dev

    - name: Configure CMake
      run: cmake -S ${{ github.workspace }} -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --parallel
